# Generated by Django 5.1.5 on 2025-02-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_alter_blogs_author_alter_blogs_blog_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/%Y/%m/%d'),
        ),
    ]
